package formatter

import "github.com/ekokurniadi/tokopedia-go-submittion/entity"

type TodoFormatter struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Status bool   `json:"status"`
}

func FormatTodo(todo entity.Todo) TodoFormatter {
	todoFormatter := TodoFormatter{}
	todoFormatter.ID = todo.ID
	todoFormatter.Title = todo.Title
	todoFormatter.Status = todo.Status
	return todoFormatter
}
func FormatTodos(todos []entity.Todo) []TodoFormatter {
	todosFormatter := []TodoFormatter{}
	for _, todo := range todos {
		todoFormatter := FormatTodo(todo)
		todosFormatter = append(todosFormatter, todoFormatter)
	}
	return todosFormatter
}

//Generated by Micagen at 11 Desember 2021
